FROM golang:1.26.6-alpine@sha256:3889b425f035be855a72fb4755265311293b6d414521f0a519d819df32222d83 AS build
ENV GOPROXY=https://proxy.golang.org
ENV GOSUMDB=sum.golang.org
WORKDIR /src
COPY infra/caddy/main.go.tmpl ./main.go
RUN go mod init family-finance/caddy \
 && caddy_json="$(go mod download -json github.com/caddyserver/caddy/v2@v2.11.4)" \
 && printf '%s\n' "$caddy_json" | grep -Fq '"Sum": "h1:XKxkMTgNSizEvKG6QHue6cAsFOteU2qA61w2tKkCWi0="' \
 && printf '%s\n' "$caddy_json" | grep -Fq '"GoModSum": "h1:zXCl032uTaF5/TpgU38axqFD41jqzxomTDNqK7BzMeI="' \
 && go get github.com/caddyserver/caddy/v2@v2.11.4 \
 && go get golang.org/x/crypto@v0.54.0 \
           golang.org/x/net@v0.57.0 \
           golang.org/x/text@v0.40.0 \
           google.golang.org/grpc@v1.82.1 \
 && go mod tidy \
 && test "$(go list -m -f '{{.Version}}' github.com/caddyserver/caddy/v2)" = 'v2.11.4' \
 && test "$(go list -m -f '{{.Version}}' golang.org/x/crypto)" = 'v0.54.0' \
 && test "$(go list -m -f '{{.Version}}' golang.org/x/net)" = 'v0.57.0' \
 && test "$(go list -m -f '{{.Version}}' golang.org/x/text)" = 'v0.40.0' \
 && test "$(go list -m -f '{{.Version}}' google.golang.org/grpc)" = 'v1.82.1'
RUN CGO_ENABLED=0 go build -trimpath -tags 'nobadger,nomysql,nopgx' -ldflags='-s -w' -o /out/caddy .

FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
RUN apk upgrade --no-cache \
 && apk add --no-cache ca-certificates tzdata su-exec \
 && apk add --no-cache --virtual .setcap-deps libcap \
 && addgroup -S -g 1000 caddy \
 && adduser -S -D -H -G caddy -u 1000 caddy \
 && mkdir -p /config/caddy /data/caddy /etc/caddy /srv \
 && chown -R 1000:1000 /config /data /etc/caddy /srv
COPY --from=build /out/caddy /usr/bin/caddy
RUN chmod 0755 /usr/bin/caddy \
 && setcap cap_net_bind_service=+ep /usr/bin/caddy \
 && apk del .setcap-deps
COPY infra/caddy/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod 0755 /usr/local/bin/docker-entrypoint.sh
ENV XDG_CONFIG_HOME=/config
ENV XDG_DATA_HOME=/data
WORKDIR /srv
EXPOSE 80 443 443/udp
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
