// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: advice_audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdviceAudit = `-- name: CreateAdviceAudit :one
INSERT INTO advice_audits (
    created_at,
    model_role,
    reviewer_role,
    data_as_of,
    prompt_template_version,
    request_sha256,
    advice_sha256,
    quality_level,
    status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at, model_role, reviewer_role, data_as_of, prompt_template_version, request_sha256, advice_sha256, quality_level, status
`

type CreateAdviceAuditParams struct {
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ModelRole             string             `json:"model_role"`
	ReviewerRole          pgtype.Text        `json:"reviewer_role"`
	DataAsOf              pgtype.Timestamptz `json:"data_as_of"`
	PromptTemplateVersion string             `json:"prompt_template_version"`
	RequestSha256         string             `json:"request_sha256"`
	AdviceSha256          string             `json:"advice_sha256"`
	QualityLevel          string             `json:"quality_level"`
	Status                string             `json:"status"`
}

func (q *Queries) CreateAdviceAudit(ctx context.Context, arg CreateAdviceAuditParams) (AdviceAudit, error) {
	row := q.db.QueryRow(ctx, createAdviceAudit,
		arg.CreatedAt,
		arg.ModelRole,
		arg.ReviewerRole,
		arg.DataAsOf,
		arg.PromptTemplateVersion,
		arg.RequestSha256,
		arg.AdviceSha256,
		arg.QualityLevel,
		arg.Status,
	)
	var i AdviceAudit
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModelRole,
		&i.ReviewerRole,
		&i.DataAsOf,
		&i.PromptTemplateVersion,
		&i.RequestSha256,
		&i.AdviceSha256,
		&i.QualityLevel,
		&i.Status,
	)
	return i, err
}

const createAdviceAuditTool = `-- name: CreateAdviceAuditTool :one
INSERT INTO advice_audit_tools (
    advice_audit_id,
    sequence,
    tool_name,
    input_sha256,
    result_sha256,
    success,
    error_code
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, advice_audit_id, sequence, tool_name, input_sha256, result_sha256, success, error_code
`

type CreateAdviceAuditToolParams struct {
	AdviceAuditID int64       `json:"advice_audit_id"`
	Sequence      int32       `json:"sequence"`
	ToolName      string      `json:"tool_name"`
	InputSha256   string      `json:"input_sha256"`
	ResultSha256  pgtype.Text `json:"result_sha256"`
	Success       bool        `json:"success"`
	ErrorCode     pgtype.Text `json:"error_code"`
}

func (q *Queries) CreateAdviceAuditTool(ctx context.Context, arg CreateAdviceAuditToolParams) (AdviceAuditTool, error) {
	row := q.db.QueryRow(ctx, createAdviceAuditTool,
		arg.AdviceAuditID,
		arg.Sequence,
		arg.ToolName,
		arg.InputSha256,
		arg.ResultSha256,
		arg.Success,
		arg.ErrorCode,
	)
	var i AdviceAuditTool
	err := row.Scan(
		&i.ID,
		&i.AdviceAuditID,
		&i.Sequence,
		&i.ToolName,
		&i.InputSha256,
		&i.ResultSha256,
		&i.Success,
		&i.ErrorCode,
	)
	return i, err
}

const getAdviceAudit = `-- name: GetAdviceAudit :one
SELECT id, created_at, model_role, reviewer_role, data_as_of, prompt_template_version, request_sha256, advice_sha256, quality_level, status
FROM advice_audits
WHERE id = $1
`

func (q *Queries) GetAdviceAudit(ctx context.Context, id int64) (AdviceAudit, error) {
	row := q.db.QueryRow(ctx, getAdviceAudit, id)
	var i AdviceAudit
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModelRole,
		&i.ReviewerRole,
		&i.DataAsOf,
		&i.PromptTemplateVersion,
		&i.RequestSha256,
		&i.AdviceSha256,
		&i.QualityLevel,
		&i.Status,
	)
	return i, err
}

const listAdviceAuditTools = `-- name: ListAdviceAuditTools :many
SELECT id, advice_audit_id, sequence, tool_name, input_sha256, result_sha256, success, error_code
FROM advice_audit_tools
WHERE advice_audit_id = $1
ORDER BY sequence ASC
`

func (q *Queries) ListAdviceAuditTools(ctx context.Context, adviceAuditID int64) ([]AdviceAuditTool, error) {
	rows, err := q.db.Query(ctx, listAdviceAuditTools, adviceAuditID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdviceAuditTool{}
	for rows.Next() {
		var i AdviceAuditTool
		if err := rows.Scan(
			&i.ID,
			&i.AdviceAuditID,
			&i.Sequence,
			&i.ToolName,
			&i.InputSha256,
			&i.ResultSha256,
			&i.Success,
			&i.ErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
