// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_tool_audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeAgentToolAuditFailure = `-- name: CompleteAgentToolAuditFailure :one
UPDATE agent_tool_audits
SET status = 'error',
    error_code = $1,
    duration_ms = $2
WHERE id = $3
  AND status = 'running'
RETURNING id
`

type CompleteAgentToolAuditFailureParams struct {
	ErrorCode  pgtype.Text `json:"error_code"`
	DurationMs pgtype.Int8 `json:"duration_ms"`
	ID         int64       `json:"id"`
}

func (q *Queries) CompleteAgentToolAuditFailure(ctx context.Context, arg CompleteAgentToolAuditFailureParams) (int64, error) {
	row := q.db.QueryRow(ctx, completeAgentToolAuditFailure, arg.ErrorCode, arg.DurationMs, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const completeAgentToolAuditSuccess = `-- name: CompleteAgentToolAuditSuccess :one
UPDATE agent_tool_audits
SET output_sha256 = $1,
    data_as_of = $2,
    status = 'success',
    duration_ms = $3
WHERE id = $4
  AND status = 'running'
RETURNING id
`

type CompleteAgentToolAuditSuccessParams struct {
	OutputSha256 pgtype.Text        `json:"output_sha256"`
	DataAsOf     pgtype.Timestamptz `json:"data_as_of"`
	DurationMs   pgtype.Int8        `json:"duration_ms"`
	ID           int64              `json:"id"`
}

func (q *Queries) CompleteAgentToolAuditSuccess(ctx context.Context, arg CompleteAgentToolAuditSuccessParams) (int64, error) {
	row := q.db.QueryRow(ctx, completeAgentToolAuditSuccess,
		arg.OutputSha256,
		arg.DataAsOf,
		arg.DurationMs,
		arg.ID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createAgentToolAuditAttempt = `-- name: CreateAgentToolAuditAttempt :one
INSERT INTO agent_tool_audits (
    created_at,
    principal_kind,
    household_id,
    protocol,
    protocol_version,
    client_name,
    client_version,
    tool_name,
    input_sha256,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    'running'
)
RETURNING id
`

type CreateAgentToolAuditAttemptParams struct {
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PrincipalKind   string             `json:"principal_kind"`
	HouseholdID     int64              `json:"household_id"`
	Protocol        string             `json:"protocol"`
	ProtocolVersion string             `json:"protocol_version"`
	ClientName      pgtype.Text        `json:"client_name"`
	ClientVersion   pgtype.Text        `json:"client_version"`
	ToolName        string             `json:"tool_name"`
	InputSha256     string             `json:"input_sha256"`
}

func (q *Queries) CreateAgentToolAuditAttempt(ctx context.Context, arg CreateAgentToolAuditAttemptParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAgentToolAuditAttempt,
		arg.CreatedAt,
		arg.PrincipalKind,
		arg.HouseholdID,
		arg.Protocol,
		arg.ProtocolVersion,
		arg.ClientName,
		arg.ClientVersion,
		arg.ToolName,
		arg.InputSha256,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAgentToolAudit = `-- name: GetAgentToolAudit :one
SELECT
    id,
    created_at,
    principal_kind,
    household_id,
    protocol,
    protocol_version,
    client_name,
    client_version,
    tool_name,
    input_sha256,
    output_sha256,
    data_as_of,
    status,
    error_code,
    duration_ms
FROM agent_tool_audits
WHERE id = $1
`

func (q *Queries) GetAgentToolAudit(ctx context.Context, id int64) (AgentToolAudit, error) {
	row := q.db.QueryRow(ctx, getAgentToolAudit, id)
	var i AgentToolAudit
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.PrincipalKind,
		&i.HouseholdID,
		&i.Protocol,
		&i.ProtocolVersion,
		&i.ClientName,
		&i.ClientVersion,
		&i.ToolName,
		&i.InputSha256,
		&i.OutputSha256,
		&i.DataAsOf,
		&i.Status,
		&i.ErrorCode,
		&i.DurationMs,
	)
	return i, err
}
