// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBudgetLine = `-- name: CreateBudgetLine :one
INSERT INTO budget_lines (
    budget_plan_id, external_category_ref, semantic_group, planned_minor, kind
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, budget_plan_id, external_category_ref, semantic_group, planned_minor, kind
`

type CreateBudgetLineParams struct {
	BudgetPlanID        int64       `json:"budget_plan_id"`
	ExternalCategoryRef pgtype.Text `json:"external_category_ref"`
	SemanticGroup       pgtype.Text `json:"semantic_group"`
	PlannedMinor        int64       `json:"planned_minor"`
	Kind                string      `json:"kind"`
}

type CreateBudgetLineRow struct {
	ID                  int64       `json:"id"`
	BudgetPlanID        int64       `json:"budget_plan_id"`
	ExternalCategoryRef pgtype.Text `json:"external_category_ref"`
	SemanticGroup       pgtype.Text `json:"semantic_group"`
	PlannedMinor        int64       `json:"planned_minor"`
	Kind                string      `json:"kind"`
}

func (q *Queries) CreateBudgetLine(ctx context.Context, arg CreateBudgetLineParams) (CreateBudgetLineRow, error) {
	row := q.db.QueryRow(ctx, createBudgetLine,
		arg.BudgetPlanID,
		arg.ExternalCategoryRef,
		arg.SemanticGroup,
		arg.PlannedMinor,
		arg.Kind,
	)
	var i CreateBudgetLineRow
	err := row.Scan(
		&i.ID,
		&i.BudgetPlanID,
		&i.ExternalCategoryRef,
		&i.SemanticGroup,
		&i.PlannedMinor,
		&i.Kind,
	)
	return i, err
}

const createBudgetPlan = `-- name: CreateBudgetPlan :one
INSERT INTO budget_plans (household_id, period, currency)
VALUES ($1, $2, $3)
RETURNING id, household_id, period, currency
`

type CreateBudgetPlanParams struct {
	HouseholdID int64  `json:"household_id"`
	Period      string `json:"period"`
	Currency    string `json:"currency"`
}

type CreateBudgetPlanRow struct {
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
	Period      string `json:"period"`
	Currency    string `json:"currency"`
}

func (q *Queries) CreateBudgetPlan(ctx context.Context, arg CreateBudgetPlanParams) (CreateBudgetPlanRow, error) {
	row := q.db.QueryRow(ctx, createBudgetPlan, arg.HouseholdID, arg.Period, arg.Currency)
	var i CreateBudgetPlanRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Period,
		&i.Currency,
	)
	return i, err
}

const getBudgetPlan = `-- name: GetBudgetPlan :one
SELECT id, household_id, period, currency
FROM budget_plans
WHERE id = $1
`

type GetBudgetPlanRow struct {
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
	Period      string `json:"period"`
	Currency    string `json:"currency"`
}

func (q *Queries) GetBudgetPlan(ctx context.Context, id int64) (GetBudgetPlanRow, error) {
	row := q.db.QueryRow(ctx, getBudgetPlan, id)
	var i GetBudgetPlanRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Period,
		&i.Currency,
	)
	return i, err
}

const getBudgetPlanByHouseholdPeriod = `-- name: GetBudgetPlanByHouseholdPeriod :one
SELECT id, household_id, period, currency
FROM budget_plans
WHERE household_id = $1 AND period = $2
`

type GetBudgetPlanByHouseholdPeriodParams struct {
	HouseholdID int64  `json:"household_id"`
	Period      string `json:"period"`
}

type GetBudgetPlanByHouseholdPeriodRow struct {
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
	Period      string `json:"period"`
	Currency    string `json:"currency"`
}

func (q *Queries) GetBudgetPlanByHouseholdPeriod(ctx context.Context, arg GetBudgetPlanByHouseholdPeriodParams) (GetBudgetPlanByHouseholdPeriodRow, error) {
	row := q.db.QueryRow(ctx, getBudgetPlanByHouseholdPeriod, arg.HouseholdID, arg.Period)
	var i GetBudgetPlanByHouseholdPeriodRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Period,
		&i.Currency,
	)
	return i, err
}

const listBudgetLines = `-- name: ListBudgetLines :many
SELECT id, budget_plan_id, external_category_ref, semantic_group, planned_minor, kind
FROM budget_lines
WHERE budget_plan_id = $1
ORDER BY id
`

type ListBudgetLinesRow struct {
	ID                  int64       `json:"id"`
	BudgetPlanID        int64       `json:"budget_plan_id"`
	ExternalCategoryRef pgtype.Text `json:"external_category_ref"`
	SemanticGroup       pgtype.Text `json:"semantic_group"`
	PlannedMinor        int64       `json:"planned_minor"`
	Kind                string      `json:"kind"`
}

func (q *Queries) ListBudgetLines(ctx context.Context, budgetPlanID int64) ([]ListBudgetLinesRow, error) {
	rows, err := q.db.Query(ctx, listBudgetLines, budgetPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetLinesRow{}
	for rows.Next() {
		var i ListBudgetLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.BudgetPlanID,
			&i.ExternalCategoryRef,
			&i.SemanticGroup,
			&i.PlannedMinor,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
