// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: debt.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (
    household_id,
    name,
    debt_type,
    original_principal_minor,
    balance_minor,
    currency,
    apr,
    rate_type,
    lpr_spread,
    term_remaining_months,
    due_day,
    repayment_type,
    minimum_payment_minor,
    scheduled_payment_minor,
    prepayment_fee_rate,
    prepayment_restricted_months,
    revolving,
    source_account_ref,
    active
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19
)
RETURNING id, household_id, name, debt_type, original_principal_minor, balance_minor, currency, apr, rate_type, lpr_spread, term_remaining_months, due_day, repayment_type, minimum_payment_minor, scheduled_payment_minor, prepayment_fee_rate, prepayment_restricted_months, revolving, source_account_ref, active, created_at, updated_at
`

type CreateDebtParams struct {
	HouseholdID                int64          `json:"household_id"`
	Name                       string         `json:"name"`
	DebtType                   string         `json:"debt_type"`
	OriginalPrincipalMinor     int64          `json:"original_principal_minor"`
	BalanceMinor               int64          `json:"balance_minor"`
	Currency                   string         `json:"currency"`
	Apr                        pgtype.Numeric `json:"apr"`
	RateType                   string         `json:"rate_type"`
	LprSpread                  pgtype.Numeric `json:"lpr_spread"`
	TermRemainingMonths        int32          `json:"term_remaining_months"`
	DueDay                     int32          `json:"due_day"`
	RepaymentType              string         `json:"repayment_type"`
	MinimumPaymentMinor        int64          `json:"minimum_payment_minor"`
	ScheduledPaymentMinor      int64          `json:"scheduled_payment_minor"`
	PrepaymentFeeRate          pgtype.Numeric `json:"prepayment_fee_rate"`
	PrepaymentRestrictedMonths int32          `json:"prepayment_restricted_months"`
	Revolving                  bool           `json:"revolving"`
	SourceAccountRef           pgtype.Text    `json:"source_account_ref"`
	Active                     bool           `json:"active"`
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, createDebt,
		arg.HouseholdID,
		arg.Name,
		arg.DebtType,
		arg.OriginalPrincipalMinor,
		arg.BalanceMinor,
		arg.Currency,
		arg.Apr,
		arg.RateType,
		arg.LprSpread,
		arg.TermRemainingMonths,
		arg.DueDay,
		arg.RepaymentType,
		arg.MinimumPaymentMinor,
		arg.ScheduledPaymentMinor,
		arg.PrepaymentFeeRate,
		arg.PrepaymentRestrictedMonths,
		arg.Revolving,
		arg.SourceAccountRef,
		arg.Active,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.DebtType,
		&i.OriginalPrincipalMinor,
		&i.BalanceMinor,
		&i.Currency,
		&i.Apr,
		&i.RateType,
		&i.LprSpread,
		&i.TermRemainingMonths,
		&i.DueDay,
		&i.RepaymentType,
		&i.MinimumPaymentMinor,
		&i.ScheduledPaymentMinor,
		&i.PrepaymentFeeRate,
		&i.PrepaymentRestrictedMonths,
		&i.Revolving,
		&i.SourceAccountRef,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDebt = `-- name: GetDebt :one
SELECT id, household_id, name, debt_type, original_principal_minor, balance_minor, currency, apr, rate_type, lpr_spread, term_remaining_months, due_day, repayment_type, minimum_payment_minor, scheduled_payment_minor, prepayment_fee_rate, prepayment_restricted_months, revolving, source_account_ref, active, created_at, updated_at
FROM debts
WHERE id = $1
`

func (q *Queries) GetDebt(ctx context.Context, id int64) (Debt, error) {
	row := q.db.QueryRow(ctx, getDebt, id)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.DebtType,
		&i.OriginalPrincipalMinor,
		&i.BalanceMinor,
		&i.Currency,
		&i.Apr,
		&i.RateType,
		&i.LprSpread,
		&i.TermRemainingMonths,
		&i.DueDay,
		&i.RepaymentType,
		&i.MinimumPaymentMinor,
		&i.ScheduledPaymentMinor,
		&i.PrepaymentFeeRate,
		&i.PrepaymentRestrictedMonths,
		&i.Revolving,
		&i.SourceAccountRef,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDebtsByHousehold = `-- name: ListDebtsByHousehold :many
SELECT id, household_id, name, debt_type, original_principal_minor, balance_minor, currency, apr, rate_type, lpr_spread, term_remaining_months, due_day, repayment_type, minimum_payment_minor, scheduled_payment_minor, prepayment_fee_rate, prepayment_restricted_months, revolving, source_account_ref, active, created_at, updated_at
FROM debts
WHERE household_id = $1
ORDER BY id
`

func (q *Queries) ListDebtsByHousehold(ctx context.Context, householdID int64) ([]Debt, error) {
	rows, err := q.db.Query(ctx, listDebtsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Debt{}
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.DebtType,
			&i.OriginalPrincipalMinor,
			&i.BalanceMinor,
			&i.Currency,
			&i.Apr,
			&i.RateType,
			&i.LprSpread,
			&i.TermRemainingMonths,
			&i.DueDay,
			&i.RepaymentType,
			&i.MinimumPaymentMinor,
			&i.ScheduledPaymentMinor,
			&i.PrepaymentFeeRate,
			&i.PrepaymentRestrictedMonths,
			&i.Revolving,
			&i.SourceAccountRef,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDebtBalance = `-- name: UpdateDebtBalance :one
UPDATE debts
SET balance_minor = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, household_id, name, debt_type, original_principal_minor, balance_minor, currency, apr, rate_type, lpr_spread, term_remaining_months, due_day, repayment_type, minimum_payment_minor, scheduled_payment_minor, prepayment_fee_rate, prepayment_restricted_months, revolving, source_account_ref, active, created_at, updated_at
`

type UpdateDebtBalanceParams struct {
	ID           int64 `json:"id"`
	BalanceMinor int64 `json:"balance_minor"`
}

func (q *Queries) UpdateDebtBalance(ctx context.Context, arg UpdateDebtBalanceParams) (Debt, error) {
	row := q.db.QueryRow(ctx, updateDebtBalance, arg.ID, arg.BalanceMinor)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.DebtType,
		&i.OriginalPrincipalMinor,
		&i.BalanceMinor,
		&i.Currency,
		&i.Apr,
		&i.RateType,
		&i.LprSpread,
		&i.TermRemainingMonths,
		&i.DueDay,
		&i.RepaymentType,
		&i.MinimumPaymentMinor,
		&i.ScheduledPaymentMinor,
		&i.PrepaymentFeeRate,
		&i.PrepaymentRestrictedMonths,
		&i.Revolving,
		&i.SourceAccountRef,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
