// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFinancialGoal = `-- name: CreateFinancialGoal :one
INSERT INTO financial_goals (
    household_id,
    name,
    target_minor,
    funded_minor,
    target_date,
    priority,
    flexibility,
    monthly_contribution_minor,
    currency,
    active
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING
    id,
    household_id,
    name,
    target_minor,
    funded_minor,
    target_date,
    priority,
    flexibility,
    monthly_contribution_minor,
    currency,
    active
`

type CreateFinancialGoalParams struct {
	HouseholdID              int64       `json:"household_id"`
	Name                     string      `json:"name"`
	TargetMinor              int64       `json:"target_minor"`
	FundedMinor              int64       `json:"funded_minor"`
	TargetDate               pgtype.Date `json:"target_date"`
	Priority                 int32       `json:"priority"`
	Flexibility              string      `json:"flexibility"`
	MonthlyContributionMinor int64       `json:"monthly_contribution_minor"`
	Currency                 string      `json:"currency"`
	Active                   bool        `json:"active"`
}

type CreateFinancialGoalRow struct {
	ID                       int64       `json:"id"`
	HouseholdID              int64       `json:"household_id"`
	Name                     string      `json:"name"`
	TargetMinor              int64       `json:"target_minor"`
	FundedMinor              int64       `json:"funded_minor"`
	TargetDate               pgtype.Date `json:"target_date"`
	Priority                 int32       `json:"priority"`
	Flexibility              string      `json:"flexibility"`
	MonthlyContributionMinor int64       `json:"monthly_contribution_minor"`
	Currency                 string      `json:"currency"`
	Active                   bool        `json:"active"`
}

func (q *Queries) CreateFinancialGoal(ctx context.Context, arg CreateFinancialGoalParams) (CreateFinancialGoalRow, error) {
	row := q.db.QueryRow(ctx, createFinancialGoal,
		arg.HouseholdID,
		arg.Name,
		arg.TargetMinor,
		arg.FundedMinor,
		arg.TargetDate,
		arg.Priority,
		arg.Flexibility,
		arg.MonthlyContributionMinor,
		arg.Currency,
		arg.Active,
	)
	var i CreateFinancialGoalRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.TargetMinor,
		&i.FundedMinor,
		&i.TargetDate,
		&i.Priority,
		&i.Flexibility,
		&i.MonthlyContributionMinor,
		&i.Currency,
		&i.Active,
	)
	return i, err
}

const getFinancialGoal = `-- name: GetFinancialGoal :one
SELECT
    id,
    household_id,
    name,
    target_minor,
    funded_minor,
    target_date,
    priority,
    flexibility,
    monthly_contribution_minor,
    currency,
    active
FROM financial_goals
WHERE id = $1
`

type GetFinancialGoalRow struct {
	ID                       int64       `json:"id"`
	HouseholdID              int64       `json:"household_id"`
	Name                     string      `json:"name"`
	TargetMinor              int64       `json:"target_minor"`
	FundedMinor              int64       `json:"funded_minor"`
	TargetDate               pgtype.Date `json:"target_date"`
	Priority                 int32       `json:"priority"`
	Flexibility              string      `json:"flexibility"`
	MonthlyContributionMinor int64       `json:"monthly_contribution_minor"`
	Currency                 string      `json:"currency"`
	Active                   bool        `json:"active"`
}

func (q *Queries) GetFinancialGoal(ctx context.Context, id int64) (GetFinancialGoalRow, error) {
	row := q.db.QueryRow(ctx, getFinancialGoal, id)
	var i GetFinancialGoalRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.TargetMinor,
		&i.FundedMinor,
		&i.TargetDate,
		&i.Priority,
		&i.Flexibility,
		&i.MonthlyContributionMinor,
		&i.Currency,
		&i.Active,
	)
	return i, err
}

const listFinancialGoalsByHousehold = `-- name: ListFinancialGoalsByHousehold :many
SELECT
    id,
    household_id,
    name,
    target_minor,
    funded_minor,
    target_date,
    priority,
    flexibility,
    monthly_contribution_minor,
    currency,
    active
FROM financial_goals
WHERE household_id = $1
ORDER BY active DESC, priority ASC, target_date ASC, id ASC
`

type ListFinancialGoalsByHouseholdRow struct {
	ID                       int64       `json:"id"`
	HouseholdID              int64       `json:"household_id"`
	Name                     string      `json:"name"`
	TargetMinor              int64       `json:"target_minor"`
	FundedMinor              int64       `json:"funded_minor"`
	TargetDate               pgtype.Date `json:"target_date"`
	Priority                 int32       `json:"priority"`
	Flexibility              string      `json:"flexibility"`
	MonthlyContributionMinor int64       `json:"monthly_contribution_minor"`
	Currency                 string      `json:"currency"`
	Active                   bool        `json:"active"`
}

func (q *Queries) ListFinancialGoalsByHousehold(ctx context.Context, householdID int64) ([]ListFinancialGoalsByHouseholdRow, error) {
	rows, err := q.db.Query(ctx, listFinancialGoalsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFinancialGoalsByHouseholdRow{}
	for rows.Next() {
		var i ListFinancialGoalsByHouseholdRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.TargetMinor,
			&i.FundedMinor,
			&i.TargetDate,
			&i.Priority,
			&i.Flexibility,
			&i.MonthlyContributionMinor,
			&i.Currency,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
