// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: household.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpenseBaseline = `-- name: CreateExpenseBaseline :one
INSERT INTO expense_baselines (
    household_id, name, amount_minor, currency, cadence, essential, active
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, household_id, name, amount_minor, currency, cadence, essential, active
`

type CreateExpenseBaselineParams struct {
	HouseholdID int64  `json:"household_id"`
	Name        string `json:"name"`
	AmountMinor int64  `json:"amount_minor"`
	Currency    string `json:"currency"`
	Cadence     string `json:"cadence"`
	Essential   bool   `json:"essential"`
	Active      bool   `json:"active"`
}

type CreateExpenseBaselineRow struct {
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
	Name        string `json:"name"`
	AmountMinor int64  `json:"amount_minor"`
	Currency    string `json:"currency"`
	Cadence     string `json:"cadence"`
	Essential   bool   `json:"essential"`
	Active      bool   `json:"active"`
}

func (q *Queries) CreateExpenseBaseline(ctx context.Context, arg CreateExpenseBaselineParams) (CreateExpenseBaselineRow, error) {
	row := q.db.QueryRow(ctx, createExpenseBaseline,
		arg.HouseholdID,
		arg.Name,
		arg.AmountMinor,
		arg.Currency,
		arg.Cadence,
		arg.Essential,
		arg.Active,
	)
	var i CreateExpenseBaselineRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.AmountMinor,
		&i.Currency,
		&i.Cadence,
		&i.Essential,
		&i.Active,
	)
	return i, err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (name, base_currency, timezone)
VALUES ($1, $2, $3)
RETURNING id, name, base_currency, timezone
`

type CreateHouseholdParams struct {
	Name         string `json:"name"`
	BaseCurrency string `json:"base_currency"`
	Timezone     string `json:"timezone"`
}

type CreateHouseholdRow struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	BaseCurrency string `json:"base_currency"`
	Timezone     string `json:"timezone"`
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (CreateHouseholdRow, error) {
	row := q.db.QueryRow(ctx, createHousehold, arg.Name, arg.BaseCurrency, arg.Timezone)
	var i CreateHouseholdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.Timezone,
	)
	return i, err
}

const createHouseholdMember = `-- name: CreateHouseholdMember :one
INSERT INTO household_members (household_id, name, kind, active)
VALUES ($1, $2, $3, $4)
RETURNING id, household_id, name, kind, active
`

type CreateHouseholdMemberParams struct {
	HouseholdID int64  `json:"household_id"`
	Name        string `json:"name"`
	Kind        string `json:"kind"`
	Active      bool   `json:"active"`
}

type CreateHouseholdMemberRow struct {
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
	Name        string `json:"name"`
	Kind        string `json:"kind"`
	Active      bool   `json:"active"`
}

func (q *Queries) CreateHouseholdMember(ctx context.Context, arg CreateHouseholdMemberParams) (CreateHouseholdMemberRow, error) {
	row := q.db.QueryRow(ctx, createHouseholdMember,
		arg.HouseholdID,
		arg.Name,
		arg.Kind,
		arg.Active,
	)
	var i CreateHouseholdMemberRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Kind,
		&i.Active,
	)
	return i, err
}

const createIncomeSource = `-- name: CreateIncomeSource :one
INSERT INTO income_sources (
    household_id, member_id, name, amount_minor, currency, cadence, stability, active
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, household_id, member_id, name, amount_minor, currency, cadence, stability, active
`

type CreateIncomeSourceParams struct {
	HouseholdID int64       `json:"household_id"`
	MemberID    pgtype.Int8 `json:"member_id"`
	Name        string      `json:"name"`
	AmountMinor int64       `json:"amount_minor"`
	Currency    string      `json:"currency"`
	Cadence     string      `json:"cadence"`
	Stability   string      `json:"stability"`
	Active      bool        `json:"active"`
}

type CreateIncomeSourceRow struct {
	ID          int64       `json:"id"`
	HouseholdID int64       `json:"household_id"`
	MemberID    pgtype.Int8 `json:"member_id"`
	Name        string      `json:"name"`
	AmountMinor int64       `json:"amount_minor"`
	Currency    string      `json:"currency"`
	Cadence     string      `json:"cadence"`
	Stability   string      `json:"stability"`
	Active      bool        `json:"active"`
}

func (q *Queries) CreateIncomeSource(ctx context.Context, arg CreateIncomeSourceParams) (CreateIncomeSourceRow, error) {
	row := q.db.QueryRow(ctx, createIncomeSource,
		arg.HouseholdID,
		arg.MemberID,
		arg.Name,
		arg.AmountMinor,
		arg.Currency,
		arg.Cadence,
		arg.Stability,
		arg.Active,
	)
	var i CreateIncomeSourceRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.Name,
		&i.AmountMinor,
		&i.Currency,
		&i.Cadence,
		&i.Stability,
		&i.Active,
	)
	return i, err
}

const getHousehold = `-- name: GetHousehold :one
SELECT id, name, base_currency, timezone
FROM households
WHERE id = $1
`

type GetHouseholdRow struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	BaseCurrency string `json:"base_currency"`
	Timezone     string `json:"timezone"`
}

func (q *Queries) GetHousehold(ctx context.Context, id int64) (GetHouseholdRow, error) {
	row := q.db.QueryRow(ctx, getHousehold, id)
	var i GetHouseholdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.Timezone,
	)
	return i, err
}

const getHouseholdPolicy = `-- name: GetHouseholdPolicy :one
SELECT household_id, liquidity_floor_minor, currency
FROM household_policies
WHERE household_id = $1
`

type GetHouseholdPolicyRow struct {
	HouseholdID         int64  `json:"household_id"`
	LiquidityFloorMinor int64  `json:"liquidity_floor_minor"`
	Currency            string `json:"currency"`
}

func (q *Queries) GetHouseholdPolicy(ctx context.Context, householdID int64) (GetHouseholdPolicyRow, error) {
	row := q.db.QueryRow(ctx, getHouseholdPolicy, householdID)
	var i GetHouseholdPolicyRow
	err := row.Scan(&i.HouseholdID, &i.LiquidityFloorMinor, &i.Currency)
	return i, err
}

const listExpenseBaselines = `-- name: ListExpenseBaselines :many
SELECT id, household_id, name, amount_minor, currency, cadence, essential, active
FROM expense_baselines
WHERE household_id = $1
ORDER BY id
`

type ListExpenseBaselinesRow struct {
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
	Name        string `json:"name"`
	AmountMinor int64  `json:"amount_minor"`
	Currency    string `json:"currency"`
	Cadence     string `json:"cadence"`
	Essential   bool   `json:"essential"`
	Active      bool   `json:"active"`
}

func (q *Queries) ListExpenseBaselines(ctx context.Context, householdID int64) ([]ListExpenseBaselinesRow, error) {
	rows, err := q.db.Query(ctx, listExpenseBaselines, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpenseBaselinesRow{}
	for rows.Next() {
		var i ListExpenseBaselinesRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.AmountMinor,
			&i.Currency,
			&i.Cadence,
			&i.Essential,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdMembers = `-- name: ListHouseholdMembers :many
SELECT id, household_id, name, kind, active
FROM household_members
WHERE household_id = $1
ORDER BY id
`

type ListHouseholdMembersRow struct {
	ID          int64  `json:"id"`
	HouseholdID int64  `json:"household_id"`
	Name        string `json:"name"`
	Kind        string `json:"kind"`
	Active      bool   `json:"active"`
}

func (q *Queries) ListHouseholdMembers(ctx context.Context, householdID int64) ([]ListHouseholdMembersRow, error) {
	rows, err := q.db.Query(ctx, listHouseholdMembers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHouseholdMembersRow{}
	for rows.Next() {
		var i ListHouseholdMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Kind,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeSources = `-- name: ListIncomeSources :many
SELECT id, household_id, member_id, name, amount_minor, currency, cadence, stability, active
FROM income_sources
WHERE household_id = $1
ORDER BY id
`

type ListIncomeSourcesRow struct {
	ID          int64       `json:"id"`
	HouseholdID int64       `json:"household_id"`
	MemberID    pgtype.Int8 `json:"member_id"`
	Name        string      `json:"name"`
	AmountMinor int64       `json:"amount_minor"`
	Currency    string      `json:"currency"`
	Cadence     string      `json:"cadence"`
	Stability   string      `json:"stability"`
	Active      bool        `json:"active"`
}

func (q *Queries) ListIncomeSources(ctx context.Context, householdID int64) ([]ListIncomeSourcesRow, error) {
	rows, err := q.db.Query(ctx, listIncomeSources, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomeSourcesRow{}
	for rows.Next() {
		var i ListIncomeSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.MemberID,
			&i.Name,
			&i.AmountMinor,
			&i.Currency,
			&i.Cadence,
			&i.Stability,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHouseholdPolicy = `-- name: UpsertHouseholdPolicy :one
INSERT INTO household_policies (household_id, liquidity_floor_minor, currency)
VALUES ($1, $2, $3)
ON CONFLICT (household_id) DO UPDATE SET
    liquidity_floor_minor = EXCLUDED.liquidity_floor_minor,
    currency = EXCLUDED.currency,
    updated_at = CURRENT_TIMESTAMP
RETURNING household_id, liquidity_floor_minor, currency
`

type UpsertHouseholdPolicyParams struct {
	HouseholdID         int64  `json:"household_id"`
	LiquidityFloorMinor int64  `json:"liquidity_floor_minor"`
	Currency            string `json:"currency"`
}

type UpsertHouseholdPolicyRow struct {
	HouseholdID         int64  `json:"household_id"`
	LiquidityFloorMinor int64  `json:"liquidity_floor_minor"`
	Currency            string `json:"currency"`
}

func (q *Queries) UpsertHouseholdPolicy(ctx context.Context, arg UpsertHouseholdPolicyParams) (UpsertHouseholdPolicyRow, error) {
	row := q.db.QueryRow(ctx, upsertHouseholdPolicy, arg.HouseholdID, arg.LiquidityFloorMinor, arg.Currency)
	var i UpsertHouseholdPolicyRow
	err := row.Scan(&i.HouseholdID, &i.LiquidityFloorMinor, &i.Currency)
	return i, err
}
