// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJobRun = `-- name: ClaimJobRun :one
INSERT INTO job_runs (
    household_id,
    job_name,
    scheduled_for,
    period,
    status,
    started_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'running',
    $5
)
ON CONFLICT (household_id, job_name, scheduled_for) DO UPDATE SET
    period = EXCLUDED.period,
    status = 'running',
    started_at = EXCLUDED.started_at,
    finished_at = NULL,
    error_code = NULL
WHERE job_runs.status = 'failed'
RETURNING id
`

type ClaimJobRunParams struct {
	HouseholdID  int64              `json:"household_id"`
	JobName      string             `json:"job_name"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	Period       string             `json:"period"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) ClaimJobRun(ctx context.Context, arg ClaimJobRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, claimJobRun,
		arg.HouseholdID,
		arg.JobName,
		arg.ScheduledFor,
		arg.Period,
		arg.StartedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const finishJobRun = `-- name: FinishJobRun :execrows
UPDATE job_runs
SET
    status = $1,
    finished_at = $2,
    error_code = $3
WHERE household_id = $4
  AND job_name = $5
  AND scheduled_for = $6
  AND status = 'running'
`

type FinishJobRunParams struct {
	Status       string             `json:"status"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	HouseholdID  int64              `json:"household_id"`
	JobName      string             `json:"job_name"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
}

func (q *Queries) FinishJobRun(ctx context.Context, arg FinishJobRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishJobRun,
		arg.Status,
		arg.FinishedAt,
		arg.ErrorCode,
		arg.HouseholdID,
		arg.JobName,
		arg.ScheduledFor,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listJobRuns = `-- name: ListJobRuns :many
SELECT id, household_id, job_name, scheduled_for, period, status, started_at, finished_at, error_code
FROM job_runs
WHERE household_id = $1
  AND job_name = $2
ORDER BY scheduled_for DESC, id DESC
`

type ListJobRunsParams struct {
	HouseholdID int64  `json:"household_id"`
	JobName     string `json:"job_name"`
}

func (q *Queries) ListJobRuns(ctx context.Context, arg ListJobRunsParams) ([]JobRun, error) {
	rows, err := q.db.Query(ctx, listJobRuns, arg.HouseholdID, arg.JobName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobRun{}
	for rows.Next() {
		var i JobRun
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.JobName,
			&i.ScheduledFor,
			&i.Period,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulerHouseholds = `-- name: ListSchedulerHouseholds :many
SELECT id, timezone
FROM households
ORDER BY id
`

type ListSchedulerHouseholdsRow struct {
	ID       int64  `json:"id"`
	Timezone string `json:"timezone"`
}

func (q *Queries) ListSchedulerHouseholds(ctx context.Context) ([]ListSchedulerHouseholdsRow, error) {
	rows, err := q.db.Query(ctx, listSchedulerHouseholds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulerHouseholdsRow{}
	for rows.Next() {
		var i ListSchedulerHouseholdsRow
		if err := rows.Scan(&i.ID, &i.Timezone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverInterruptedJobRuns = `-- name: RecoverInterruptedJobRuns :execrows
UPDATE job_runs
SET
    status = 'failed',
    finished_at = $1,
    error_code = 'process_restarted'
WHERE status = 'running'
`

func (q *Queries) RecoverInterruptedJobRuns(ctx context.Context, recoveredAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, recoverInterruptedJobRuns, recoveredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
