// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdviceAudit struct {
	ID                    int64              `json:"id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ModelRole             string             `json:"model_role"`
	ReviewerRole          pgtype.Text        `json:"reviewer_role"`
	DataAsOf              pgtype.Timestamptz `json:"data_as_of"`
	PromptTemplateVersion string             `json:"prompt_template_version"`
	RequestSha256         string             `json:"request_sha256"`
	AdviceSha256          string             `json:"advice_sha256"`
	QualityLevel          string             `json:"quality_level"`
	Status                string             `json:"status"`
}

type AdviceAuditTool struct {
	ID            int64       `json:"id"`
	AdviceAuditID int64       `json:"advice_audit_id"`
	Sequence      int32       `json:"sequence"`
	ToolName      string      `json:"tool_name"`
	InputSha256   string      `json:"input_sha256"`
	ResultSha256  pgtype.Text `json:"result_sha256"`
	Success       bool        `json:"success"`
	ErrorCode     pgtype.Text `json:"error_code"`
}

type AgentToolAudit struct {
	ID              int64              `json:"id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PrincipalKind   string             `json:"principal_kind"`
	HouseholdID     int64              `json:"household_id"`
	Protocol        string             `json:"protocol"`
	ProtocolVersion string             `json:"protocol_version"`
	ClientName      pgtype.Text        `json:"client_name"`
	ClientVersion   pgtype.Text        `json:"client_version"`
	ToolName        string             `json:"tool_name"`
	InputSha256     string             `json:"input_sha256"`
	OutputSha256    pgtype.Text        `json:"output_sha256"`
	DataAsOf        pgtype.Timestamptz `json:"data_as_of"`
	Status          string             `json:"status"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	DurationMs      pgtype.Int8        `json:"duration_ms"`
}

type AuthChallenge struct {
	ID                          int64              `json:"id"`
	TokenHash                   []byte             `json:"token_hash"`
	UserID                      int64              `json:"user_id"`
	Kind                        string             `json:"kind"`
	PendingTotpSecretCiphertext []byte             `json:"pending_totp_secret_ciphertext"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt                   pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt                  pgtype.Timestamptz `json:"consumed_at"`
}

type AuthRecoveryCode struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	CodeHash   []byte             `json:"code_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

type AuthSession struct {
	ID                  int64              `json:"id"`
	TokenHash           []byte             `json:"token_hash"`
	UserID              int64              `json:"user_id"`
	CsrfTokenHash       []byte             `json:"csrf_token_hash"`
	CsrfTokenCiphertext []byte             `json:"csrf_token_ciphertext"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	LastSeenAt          pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
}

type AuthUser struct {
	ID                   int64              `json:"id"`
	Username             string             `json:"username"`
	NormalizedUsername   string             `json:"normalized_username"`
	PasswordHash         string             `json:"password_hash"`
	HouseholdID          int64              `json:"household_id"`
	TotpSecretCiphertext []byte             `json:"totp_secret_ciphertext"`
	TotpLastCounter      pgtype.Int8        `json:"totp_last_counter"`
	TotpEnrolledAt       pgtype.Timestamptz `json:"totp_enrolled_at"`
	DisabledAt           pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type BudgetLine struct {
	ID                  int64              `json:"id"`
	BudgetPlanID        int64              `json:"budget_plan_id"`
	ExternalCategoryRef pgtype.Text        `json:"external_category_ref"`
	SemanticGroup       pgtype.Text        `json:"semantic_group"`
	PlannedMinor        int64              `json:"planned_minor"`
	Kind                string             `json:"kind"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type BudgetPlan struct {
	ID          int64              `json:"id"`
	HouseholdID int64              `json:"household_id"`
	Period      string             `json:"period"`
	Currency    string             `json:"currency"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Debt struct {
	ID                         int64              `json:"id"`
	HouseholdID                int64              `json:"household_id"`
	Name                       string             `json:"name"`
	DebtType                   string             `json:"debt_type"`
	OriginalPrincipalMinor     int64              `json:"original_principal_minor"`
	BalanceMinor               int64              `json:"balance_minor"`
	Currency                   string             `json:"currency"`
	Apr                        pgtype.Numeric     `json:"apr"`
	RateType                   string             `json:"rate_type"`
	LprSpread                  pgtype.Numeric     `json:"lpr_spread"`
	TermRemainingMonths        int32              `json:"term_remaining_months"`
	DueDay                     int32              `json:"due_day"`
	RepaymentType              string             `json:"repayment_type"`
	MinimumPaymentMinor        int64              `json:"minimum_payment_minor"`
	ScheduledPaymentMinor      int64              `json:"scheduled_payment_minor"`
	PrepaymentFeeRate          pgtype.Numeric     `json:"prepayment_fee_rate"`
	PrepaymentRestrictedMonths int32              `json:"prepayment_restricted_months"`
	Revolving                  bool               `json:"revolving"`
	SourceAccountRef           pgtype.Text        `json:"source_account_ref"`
	Active                     bool               `json:"active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type ExpenseBaseline struct {
	ID          int64              `json:"id"`
	HouseholdID int64              `json:"household_id"`
	Name        string             `json:"name"`
	AmountMinor int64              `json:"amount_minor"`
	Currency    string             `json:"currency"`
	Cadence     string             `json:"cadence"`
	Essential   bool               `json:"essential"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type FinancialGoal struct {
	ID                       int64              `json:"id"`
	HouseholdID              int64              `json:"household_id"`
	Name                     string             `json:"name"`
	TargetMinor              int64              `json:"target_minor"`
	FundedMinor              int64              `json:"funded_minor"`
	TargetDate               pgtype.Date        `json:"target_date"`
	Priority                 int32              `json:"priority"`
	Flexibility              string             `json:"flexibility"`
	MonthlyContributionMinor int64              `json:"monthly_contribution_minor"`
	Currency                 string             `json:"currency"`
	Active                    bool               `json:"active"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type Household struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	BaseCurrency string             `json:"base_currency"`
	Timezone     string             `json:"timezone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type HouseholdMember struct {
	ID          int64              `json:"id"`
	HouseholdID int64              `json:"household_id"`
	Name        string             `json:"name"`
	Kind        string             `json:"kind"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type HouseholdPolicy struct {
	HouseholdID         int64              `json:"household_id"`
	LiquidityFloorMinor int64              `json:"liquidity_floor_minor"`
	Currency            string             `json:"currency"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type IncomeSource struct {
	ID          int64              `json:"id"`
	HouseholdID int64              `json:"household_id"`
	MemberID    pgtype.Int8        `json:"member_id"`
	Name        string             `json:"name"`
	AmountMinor int64              `json:"amount_minor"`
	Currency    string             `json:"currency"`
	Cadence     string             `json:"cadence"`
	Stability   string             `json:"stability"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type JobRun struct {
	ID           int64              `json:"id"`
	HouseholdID  int64              `json:"household_id"`
	JobName      string             `json:"job_name"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	Period       string             `json:"period"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorCode    pgtype.Text        `json:"error_code"`
}

type MonthlyReport struct {
	ID          int64              `json:"id"`
	HouseholdID int64              `json:"household_id"`
	Period      string             `json:"period"`
	Kind        string             `json:"kind"`
	DataAsOf    pgtype.Timestamptz `json:"data_as_of"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	Quality     string             `json:"quality"`
	ContentHash string             `json:"content_hash"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PortfolioAssetSnapshot struct {
	HouseholdID      int64              `json:"household_id"`
	AssetRef         string             `json:"asset_ref"`
	Name             string             `json:"name"`
	AssetClass       string             `json:"asset_class"`
	ValueMinor       int64              `json:"value_minor"`
	Currency         string             `json:"currency"`
	SourceCurrency   string             `json:"source_currency"`
	ValuationAsOf    pgtype.Timestamptz `json:"valuation_as_of"`
	FxAsOf           pgtype.Timestamptz `json:"fx_as_of"`
	SourceAccountRef pgtype.Text        `json:"source_account_ref"`
	SourceKind       string             `json:"source_kind"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
