// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ExpenseBaseline struct {
	ID          int64              `json:"id"`
	HouseholdID int64              `json:"household_id"`
	Name        string             `json:"name"`
	AmountMinor int64              `json:"amount_minor"`
	Currency    string             `json:"currency"`
	Cadence     string             `json:"cadence"`
	Essential   bool               `json:"essential"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Household struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	BaseCurrency string             `json:"base_currency"`
	Timezone     string             `json:"timezone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type HouseholdMember struct {
	ID          int64              `json:"id"`
	HouseholdID int64              `json:"household_id"`
	Name        string             `json:"name"`
	Kind        string             `json:"kind"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type HouseholdPolicy struct {
	HouseholdID         int64              `json:"household_id"`
	LiquidityFloorMinor int64              `json:"liquidity_floor_minor"`
	Currency            string             `json:"currency"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type IncomeSource struct {
	ID          int64              `json:"id"`
	HouseholdID int64              `json:"household_id"`
	MemberID    pgtype.Int8        `json:"member_id"`
	Name        string             `json:"name"`
	AmountMinor int64              `json:"amount_minor"`
	Currency    string             `json:"currency"`
	Cadence     string             `json:"cadence"`
	Stability   string             `json:"stability"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
