// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portfolio.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePortfolioAssetSnapshot = `-- name: DeletePortfolioAssetSnapshot :exec
DELETE FROM portfolio_asset_snapshots
WHERE household_id = $1
  AND asset_ref = $2
`

type DeletePortfolioAssetSnapshotParams struct {
	HouseholdID int64  `json:"household_id"`
	AssetRef    string `json:"asset_ref"`
}

func (q *Queries) DeletePortfolioAssetSnapshot(ctx context.Context, arg DeletePortfolioAssetSnapshotParams) error {
	_, err := q.db.Exec(ctx, deletePortfolioAssetSnapshot, arg.HouseholdID, arg.AssetRef)
	return err
}

const listPortfolioAssetSnapshotsByHousehold = `-- name: ListPortfolioAssetSnapshotsByHousehold :many
SELECT
    household_id,
    asset_ref,
    name,
    asset_class,
    value_minor,
    currency,
    source_currency,
    valuation_as_of,
    fx_as_of,
    source_account_ref,
    source_kind
FROM portfolio_asset_snapshots
WHERE household_id = $1
ORDER BY asset_ref ASC
`

type ListPortfolioAssetSnapshotsByHouseholdRow struct {
	HouseholdID      int64              `json:"household_id"`
	AssetRef         string             `json:"asset_ref"`
	Name             string             `json:"name"`
	AssetClass       string             `json:"asset_class"`
	ValueMinor       int64              `json:"value_minor"`
	Currency         string             `json:"currency"`
	SourceCurrency   string             `json:"source_currency"`
	ValuationAsOf    pgtype.Timestamptz `json:"valuation_as_of"`
	FxAsOf           pgtype.Timestamptz `json:"fx_as_of"`
	SourceAccountRef pgtype.Text        `json:"source_account_ref"`
	SourceKind       string             `json:"source_kind"`
}

func (q *Queries) ListPortfolioAssetSnapshotsByHousehold(ctx context.Context, householdID int64) ([]ListPortfolioAssetSnapshotsByHouseholdRow, error) {
	rows, err := q.db.Query(ctx, listPortfolioAssetSnapshotsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPortfolioAssetSnapshotsByHouseholdRow{}
	for rows.Next() {
		var i ListPortfolioAssetSnapshotsByHouseholdRow
		if err := rows.Scan(
			&i.HouseholdID,
			&i.AssetRef,
			&i.Name,
			&i.AssetClass,
			&i.ValueMinor,
			&i.Currency,
			&i.SourceCurrency,
			&i.ValuationAsOf,
			&i.FxAsOf,
			&i.SourceAccountRef,
			&i.SourceKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPortfolioAssetSnapshot = `-- name: UpsertPortfolioAssetSnapshot :one
INSERT INTO portfolio_asset_snapshots (
    household_id,
    asset_ref,
    name,
    asset_class,
    value_minor,
    currency,
    source_currency,
    valuation_as_of,
    fx_as_of,
    source_account_ref,
    source_kind
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (household_id, asset_ref) DO UPDATE SET
    name = EXCLUDED.name,
    asset_class = EXCLUDED.asset_class,
    value_minor = EXCLUDED.value_minor,
    currency = EXCLUDED.currency,
    source_currency = EXCLUDED.source_currency,
    valuation_as_of = EXCLUDED.valuation_as_of,
    fx_as_of = EXCLUDED.fx_as_of,
    source_account_ref = EXCLUDED.source_account_ref,
    source_kind = EXCLUDED.source_kind,
    updated_at = CURRENT_TIMESTAMP
RETURNING
    household_id,
    asset_ref,
    name,
    asset_class,
    value_minor,
    currency,
    source_currency,
    valuation_as_of,
    fx_as_of,
    source_account_ref,
    source_kind
`

type UpsertPortfolioAssetSnapshotParams struct {
	HouseholdID      int64              `json:"household_id"`
	AssetRef         string             `json:"asset_ref"`
	Name             string             `json:"name"`
	AssetClass       string             `json:"asset_class"`
	ValueMinor       int64              `json:"value_minor"`
	Currency         string             `json:"currency"`
	SourceCurrency   string             `json:"source_currency"`
	ValuationAsOf    pgtype.Timestamptz `json:"valuation_as_of"`
	FxAsOf           pgtype.Timestamptz `json:"fx_as_of"`
	SourceAccountRef pgtype.Text        `json:"source_account_ref"`
	SourceKind       string             `json:"source_kind"`
}

type UpsertPortfolioAssetSnapshotRow struct {
	HouseholdID      int64              `json:"household_id"`
	AssetRef         string             `json:"asset_ref"`
	Name             string             `json:"name"`
	AssetClass       string             `json:"asset_class"`
	ValueMinor       int64              `json:"value_minor"`
	Currency         string             `json:"currency"`
	SourceCurrency   string             `json:"source_currency"`
	ValuationAsOf    pgtype.Timestamptz `json:"valuation_as_of"`
	FxAsOf           pgtype.Timestamptz `json:"fx_as_of"`
	SourceAccountRef pgtype.Text        `json:"source_account_ref"`
	SourceKind       string             `json:"source_kind"`
}

func (q *Queries) UpsertPortfolioAssetSnapshot(ctx context.Context, arg UpsertPortfolioAssetSnapshotParams) (UpsertPortfolioAssetSnapshotRow, error) {
	row := q.db.QueryRow(ctx, upsertPortfolioAssetSnapshot,
		arg.HouseholdID,
		arg.AssetRef,
		arg.Name,
		arg.AssetClass,
		arg.ValueMinor,
		arg.Currency,
		arg.SourceCurrency,
		arg.ValuationAsOf,
		arg.FxAsOf,
		arg.SourceAccountRef,
		arg.SourceKind,
	)
	var i UpsertPortfolioAssetSnapshotRow
	err := row.Scan(
		&i.HouseholdID,
		&i.AssetRef,
		&i.Name,
		&i.AssetClass,
		&i.ValueMinor,
		&i.Currency,
		&i.SourceCurrency,
		&i.ValuationAsOf,
		&i.FxAsOf,
		&i.SourceAccountRef,
		&i.SourceKind,
	)
	return i, err
}
